#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ratel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ratel-webterminal
  namespace: ratel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratel-webterminal
  namespace: ratel
  labels:
    app: ratel-webterminal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratel-webterminal
  template:
    metadata:
      labels:
        app: ratel-webterminal
    spec:
      serviceAccount: ratel-webterminal
      containers:
      - name: ratel-webterminal
        image: hybfkuf/ratel-webterminal:latest
        imagePullPolicy: Always
        #args:
        #- --log-format=json
        ports:
        - name: http-web
          containerPort: 8080
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http-web
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 30
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http-web
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
          failureThreshold: 30
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ratel-webterminal
  namespace: ratel
  labels:
    app: ratel-webterminal
spec:
  selector:
    app: ratel-webterminal
  ports:
  - name: http
    port: 80
    targetPort: http-web
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratel-webterminal
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ratel-webterminal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ratel-webterminal
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: ratel-webterminal
  namespace: ratel
